### ISSUE TITLE
my alexa dose noe run on my terminal 

### ISSUE THREAD

**Issue by sebasop320** [ProgrammingHero1/romantic-alexa#12]
Hello 

when i run alexa on pycharm it works and whne i run it on the terminal seds me this error 
![Captura de Pantalla 2020-12-16 a la(s) 8 06 03 a  m](https://user-images.githubusercontent.com/73962362/102352263-9648a980-3f75-11eb-97d3-414672feabe8.JPG)

**Comment by sebasop320** [comment]
can sombe body help me pls

**Comment by ashraf-minhaj** [comment]
You need to install libraries first. Follow the commands on readme of this repository. You need to pip install them.
like this `pip install speechRecognition`

**Comment by sebasop320** [comment]
> You need to install libraries first. Follow the commands on readme of this repository. You need to pip install them.
> like this `pip install speechRecognition`

i'v install all the libraries

**Comment by naveenkk944** [comment]
check the path where you have installed ur libraries

**Comment by ashraf-minhaj** [comment]
> > You need to install libraries first. Follow the commands on readme of this repository. You need to pip install them.
> > like this `pip install speechRecognition`
> 
> i'v install all the libraries

Then the problem is while installing python you haven't  added it to environment variable path. 
Reinstall/modify install and check the box that says 'add path to environment variable'

**Comment by ajaygtm71** [comment]
have you install all pip packages from same terminal or from pycharm?

**Comment by naveenkk944** [comment]
Now its working bro rhanks for your help and response feel very greatful
seeing ur reaponse thank you
