### ISSUE TITLE
How can I get a French speech and recognition

### ISSUE THREAD

**Issue by Astryder** [ProgrammingHero1/romantic-alexa#14]
Hi folks!

I'm french and I would like to know how can I have this system in French?

Best regards

Nicolas

**Comment by ashraf-minhaj** [comment]
You need to install sphinx to do so. Read this readme - https://github.com/Uberi/speech_recognition

**Comment by ajaygtm71** [comment]
to take commands in french: 
` command = listener.recognize_google(voice,language='fr-FR') ` @Astryder
