### ISSUE TITLE
How to resolve this ?

### ISSUE THREAD

**Issue by sabab009** [ProgrammingHero1/romantic-alexa#15]
how to set something in command variable by default because if we don't say anything then it is showing an error message, it requires to listen to something everything. after saying play something it goes to youtube but next time when I return to Pycharm then it is showing error message so we need to set something by default to the command so that if we don't say anything to it , it won't show any error.

**Comment by ashraf-minhaj** [comment]
Use a while loop and try statement. 
Try will do the job you are looking for. 
`try:
    # do these
except:
    pass
`

That's it.

**Comment by sabab009** [comment]
Thank you so much Just love your channel and Hope Grandma Live Long.
