### ISSUE TITLE
UnboundLocalError: local variable 'command' referenced before assignment

### ISSUE THREAD

**Issue by alMubarmij** [ProgrammingHero1/romantic-alexa#17]
- [ ] Error output:

> D:\Python\Romantic-Alexa>main.py
> Traceback (most recent call last):
>   File "D:\Python\Romantic-Alexa\main.py",
> line 60, in <module>
>     run_alexa()
>   File "D:\Python\Romantic-Alexa\main.py",
> line 35, in run_alexa
>     command = take_command()
>   File "D:\Python\Romantic-Alexa\main.py",
> line 31, in take_command
>     return command
> **UnboundLocalError: local variable 'command' referenced before assignment**

**Comment by alMubarmij** [comment]
All required libraries have been installed.

**Comment by naveenkk944** [comment]
same error for me too

**Comment by ashraf-minhaj** [comment]
See the issue #5
