### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by ashercarson** [ProgrammingHero1/romantic-alexa#20]
I just copied and pasted it. but the error has occurred.

**UnboundLocalError: local variable 'command' referenced before assignment**

**Comment by Sdey702** [comment]
I think you have to install all packegs & check the variable or line space or gap in your code.
some time spaces is misssing

**Comment by ashercarson** [comment]
> I think you have to install all packegs & check the variable or line space or gap in your code.
> some time spaces is misssing

I checked all of it. 
and still doesn't work.
There are also people who have the same error as me when you look at the comments.

**Comment by ajaygtm71** [comment]
see #28

**Comment by ajaygtm71** [comment]
> > I think you have to install all packegs & check the variable or line space or gap in your code.
> > some time spaces is misssing
> 
> I checked all of it.
> and still doesn't work.
> There are also people who have the same error as me when you look at the comments.

see #28
