### ISSUE TITLE
I can't figure out how to solve it

### ISSUE THREAD

**Issue by SkJameelAkhtar** [ProgrammingHero1/romantic-alexa#21]
![alexa error](https://user-images.githubusercontent.com/76216831/102627088-b216a000-416d-11eb-99a2-d0cb571889a6.PNG)

can anyone please say what to do?
I'm not getting it despite going through the entire program.

**Comment by LaxmyNarayan2047118** [comment]
you have to change voice to voices in :    engine.setProperty('voices',voices[1].id)

**Comment by SkJameelAkhtar** [comment]
The error is still persisting.

It says so: (Image attached)
I'm attaching the python file also with modifications as you said.

**Comment by LaxmyNarine** [comment]
Okay it's because the voices don't have any voice at index 1 
So try changing it to 0 and try

**Comment by ashraf-minhaj** [comment]
Try this code - [Voice Id Checker](https://github.com/ashraf-minhaj/Audio-Book/blob/master/voice_id_checker.py)

**Comment by 42sol-eu** [comment]
I would say your voices list is empty or has only one entry.

try this:

ˋˋˋpython
voices = engine.getProperty('voices')
print('found ' + len(voices) + ' voices') #<– insert this. The result must be at least 2 ...
engine.setProperty('voice', voices[1].id)
ˋˋˋ

**Comment by 42sol-eu** [comment]
@ashraf-minhaj maybe close this.

**Comment by SkJameelAkhtar** [comment]
Well, I figured it out!
It is solved now!
