### ISSUE TITLE
please reply sir

### ISSUE THREAD

**Issue by Aadithyaraj** [ProgrammingHero1/romantic-alexa#23]
Traceback (most recent call last):
  File "C:/Users/Aadi/Downloads/MEmu Download/Free_Fire_com.dts.freefireth/ALEXA/main.py", line 60, in <module>
    run_alexa()
  File "C:/Users/Aadi/Downloads/MEmu Download/Free_Fire_com.dts.freefireth/ALEXA/main.py", line 35, in run_alexa
    command = take_command()
  File "C:/Users/Aadi/Downloads/MEmu Download/Free_Fire_com.dts.freefireth/ALEXA/main.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by cyberjoeone** [comment]
I'm having the same issue as above.

**Comment by LaxmyNarine** [comment]
goto python terminal in pycharm 
type 1. --> pip install pipwin
after installing pipwin
type 2. --> pipwin install pyaudio

**Comment by cyberjoeone** [comment]
I have already done the audio and all the other imports  the code runs but apparently it dose not hear the microphone built in to laptop running Linux mint 20 which works in built-in apps but not in python trying to find a solution. Thank you very much for your code and help. I'll let you know if I discover a solution.

**Comment by lbracko** [comment]
I get the same error on Mac

**Comment by Stroper111** [comment]
See issue #30 for the reason why you get `UnboundLocalError`. By changing the bare exception, you will find the real problem.

**Comment by ashraf-minhaj** [comment]
Or see the issue #5
