### ISSUE TITLE
Error Help!!!

### ISSUE THREAD

**Issue by 24-Tejas** [ProgrammingHero1/romantic-alexa#25]
Traceback (most recent call last):
        line 11, in <module>
    engine.setProperty('voice', voices[1].id)
IndexError: list index out of range

**Comment by Lokesh2Lokesh** [comment]
While trying to run this proggram im getting the error stating that : local variable command referenced before assignments.

**Comment by ashraf-minhaj** [comment]
Try this code - https://github.com/ashraf-minhaj/Audio-Book/blob/master/voice_id_checker.py
