### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by Vasukommi** [ProgrammingHero1/romantic-alexa#28]
C:\Users\vasuk\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/vasuk/PycharmProjects/pythonProject/main.py
Hello from the creator of pywhatkit, Ankit Raj Mahapatra.
Kindly do report bugs if any
What's new:
1. Fixed text_to_handwriting() function.
2. Added pywhatkit.help.<function name> for ease of use.
3. Added feature to schedule message in a group.
listening...
Traceback (most recent call last):
  File "C:\Users\vasuk\PycharmProjects\pythonProject\main.py", line 60, in <module>
    run_alexa()
  File "C:\Users\vasuk\PycharmProjects\pythonProject\main.py", line 35, in run_alexa
    command = take_command()
  File "C:\Users\vasuk\PycharmProjects\pythonProject\main.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

Process finished with exit code 1

**Comment by ajaygtm71** [comment]
go to console:  `pip install pipwin`  then  `pipwin install pyaudio` then try to run again

**Comment by nityaprakash10** [comment]
> go to console: `pip install pipwin` then `pipwin install pyaudio` then try to run again

can we do this in ubuntu?

**Comment by ashraf-minhaj** [comment]
> > go to console: `pip install pipwin` then `pipwin install pyaudio` then try to run again
> 
> can we do this in ubuntu?

Yes you can. Make sure to change the commands like this -
`pip3 install pyAudio`

`sudo apt-get install espeak`

`pip3 install pyttsx3`

For command error see issure #5
