### ISSUE TITLE
I am a little new to programming and I wrote the same code in vs code and installed everything with pip but still I am getting an error

### ISSUE THREAD

**Issue by whoschisa** [ProgrammingHero1/romantic-alexa#29]
I am a little new to programming and I wrote the same code in vs code and installed everything with pip but still I am getting an error - 

PS C:\Users\HP\OneDrive\Documents\GitHub\romantic-alexa> & C:/Users/HP/AppData/Local/Programs/Python/Python38-32/python.exe c:/Users/HP/OneDrive/Documents/GitHub/romantic-alexa/main.py
Traceback (most recent call last):
  File "c:/Users/HP/OneDrive/Documents/GitHub/romantic-alexa/main.py", line 60, in <module>
    run_alexa()
  File "c:/Users/HP/OneDrive/Documents/GitHub/romantic-alexa/main.py", line 35, in run_alexa
    command = take_command()
  File "c:/Users/HP/OneDrive/Documents/GitHub/romantic-alexa/main.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment
PS C:\Users\HP\OneDrive\Documents\GitHub\romantic-alexa> 

Please help me @ashraf-minhaj or @ProgrammingHero1

**Comment by TonyMerlyn** [comment]
I got the exact issue, I have no idea how to fix it.

**Comment by TonyMerlyn** [comment]
I used pycharm for mine, not vscode, I also have every package installed

**Comment by Stroper111** [comment]
See issue #30, the bare except is catching the real problem.

**Comment by ashraf-minhaj** [comment]
See issue #5
