### ISSUE TITLE
I can't rectify rhis error can anyone please solve

### ISSUE THREAD

**Issue by dattalucky** [ProgrammingHero1/romantic-alexa#34]
![Screenshot 2020-12-30 123237](https://user-images.githubusercontent.com/40064308/103336161-3be33900-4a9d-11eb-9f00-edbae18c9b4b.png)

**Comment by himanshu0404** [comment]
Yes this same error , i am getting

**Comment by ghost** [comment]
yah, i am also getting same error

**Comment by varunguptha** [comment]
me tooo

**Comment by NirbhayVachhani** [comment]
me too

**Comment by Sumit2889** [comment]
I faced the same issue.
Try these commands in terminal:
pip install pipwin
pipwin install pyaudio

**Comment by ashraf-minhaj** [comment]
> ![Screenshot 2020-12-30 123237](https://user-images.githubusercontent.com/40064308/103336161-3be33900-4a9d-11eb-9f00-edbae18c9b4b.png)
See this issue #5

**Comment by dattalucky** [comment]
> > ![Screenshot 2020-12-30 123237](https://user-images.githubusercontent.com/40064308/103336161-3be33900-4a9d-11eb-9f00-edbae18c9b4b.png)
> > See this issue #5

no bro it cannot  working it showing same error
