### ISSUE TITLE
UnboundLocalError: local variable 'command' referenced before assignment

### ISSUE THREAD

**Issue by wiraj1** [ProgrammingHero1/romantic-alexa#4]
I don't know why this error is coming in my code . I am taking reference from your video . As I seen in your video you have repeated the word 'command' many times but no error has came . In my code this error is coming.

Traceback (most recent call last):
  File "c:/Users/user/VS Code Projects/JAR.py", line 60, in <module>
    run_jarvis()
  File "c:/Users/user/VS Code Projects/JAR.py", line 35, in run_jarvis
    command = take_Command()
  File "c:/Users/user/VS Code Projects/JAR.py", line 31, in take_Command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

I am writing this code in VS Code and I am using python 3.8.6 .

Hope you will help me.
Thanks
from @Wiraj1
to @ProgrammingHero1

**Comment by ashraf-minhaj** [comment]
See this post's comment - https://github.com/ProgrammingHero1/romantic-alexa/issues/5
