### ISSUE TITLE
Program Ends Without Any Voice Detection

### ISSUE THREAD

**Issue by ibshafique** [ProgrammingHero1/romantic-alexa#45]
I was just trying the part of the video where the voice recognition was being tested.
But the program just ends without any error.
Does not take in any voice input.

**Process finished with exit code 0**

Here is my code:

import speech_recognition as sr
listener = sr.Recognizer()
try:
    with sr.Microphone() as source:
        print("listening...")
        voice = listener.listen(source)
        command = listener.recognize_google(voice)
        print(command)
except:
    pass

I have downloaded and installed all of the required packages using:

pip install speechRecognition pyttsx3 pywhatkit wikipedia pyjokes

**Comment by EJL3** [comment]
try to add exit() in the code, try triggering it using command line code in your case.
 def command():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print('Command Me.....')
        r.pause_threshold = 1
        audio = r.listen(source)

    try:
        print('Taking Command!!!')
        query = r.recognize_google(audio, language='en')

    except Exception as e:
        print('please repeat..')
        return "None"
    return query

while True:
    query = command().lower()

**Comment by sai-create** [comment]
Are the indentations proper in the above? Its returning errod code 1

import speech_recognition as sr

def command():
r = sr.Recognizer()
with sr.Microphone() as source:
print('Command Me..')
r.pause_threshold = 1
audio = r.listen(source)
 try:
     print('Taking command..')
     query = r.recognize_google(audio , language = 'en')
 except Exception as e:
     print('please repeat..')
 return "None"
 return query


while True:
query = command().lower()

-----------------

C:\Users\sai\PycharmProjects\Hini\venv\Scripts\python.exe C:/Users/sai/PycharmProjects/Hini/main.py
  File "C:/Users/sai/PycharmProjects/Hini/main.py", line 4
    r = sr.Recognizer()
    ^
IndentationError: expected an indented block

Process finished with exit code 1

**Comment by EJL3** [comment]
The identation above mentioned is not correct, just given the code for understanding, i will provide it with correct ident block.
#code
def command():

    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Command Me..")
        r.pause_threshold = 1
        audio = r.listen(source)

    try:
        print("Taking command...")
        query = r.recognize_google(audio, language='en')
        print(f'User Said: {query}')

    except Exception as e:

        print("Please repeat..")
        return "None"
    return query
while True:
    query = command().lower()

**Comment by Amit89499** [comment]
i Have used your code but still facing the same issue.........
the code is ending with.........
Process finished with exit code 0

**Comment by EJL3** [comment]
@Amit89499  i have done a programme in my repo named friday. Your free to use the code to solve your problem. If any issues cnct me
