### ISSUE TITLE
UnboundLocalError: local variable 'command' referenced before assignment

### ISSUE THREAD

**Issue by AlessioLami** [ProgrammingHero1/romantic-alexa#5]
Hello programming hero, first of all I would like to say thank you for this beautiful tutorial.
But unfortunately when I run the project, it gives me this error: 

UnboundLocalError: local variable 'command' referenced before assignment.

How can I fix it?
Thank you so much.

**Comment by prabureddy** [comment]
Replace the function with this code below

```
def take_command():
    command = False
    try:
        with sr.Microphone() as source:
            print('listening...')
            voice = listener.listen(source)
            command = listener.recognize_google(voice)
            command = command.lower()
            if 'alexa' in command:
                command = command.replace('alexa', '')
                print(command)
                return command
    except:

        pass
    return command


def run_alexa():
    command = take_command()
    if command == False:
        return
    print(command)
    if 'play' in command:
        song = command.replace('play', '')
        talk('playing ' + song)
        pywhatkit.playonyt(song)
    elif 'time' in command:
        time = datetime.datetime.now().strftime('%I:%M %p')
        talk('Current time is ' + time)
    elif 'who the heck is' in command:
        person = command.replace('who the heck is', '')
        info = wikipedia.summary(person, 1)
        print(info)
        talk(info)
    elif 'date' in command:
        talk('sorry, I have a headache')
    elif 'are you single' in command:
        talk('I am in a relationship with wifi')
    elif 'joke' in command:
        talk(pyjokes.get_joke())
    else:
        talk('Please say the command again.')
```

**Comment by ashraf-minhaj** [comment]
This may happen if your listener returns None. 
In that case make sure you have a decent internet connection . Also try putting 
`print(command)`
after you receive the command to see if there exists any command string.

**Comment by TakaoDev** [comment]
Thakyou so much ashraf-minhaj.

**Comment by cyberjoeone** [comment]
Ok made the above change to the code, thank you, but now no errors but no response in terminal. any thoughts?

**Comment by prabureddy** [comment]
Ok, Add print statement where ever you want

**Comment by BenEgeTR** [comment]
it just keeps listening to me it doesnt recognize my voice or anything
listening...
listening...
listening...
listening...
listening...
listening...
listening...

**Comment by jayasri1616** [comment]
same thing happened with my code .could you please resolve it
