### ISSUE TITLE
Not able to run it without an error, even after following the whole process given in youtube

### ISSUE THREAD

**Issue by Pluckhimout** [ProgrammingHero1/romantic-alexa#50]
This input is the same thing given by Programming Hero:
Input:

`import speech_recognition as sr
import pyttsx3
import pywhatkit
import datetime
import wikipedia
import pyjokes

listener = sr.Recognizer()
engine = pyttsx3.init()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)

def talk(text):
    engine.say(text)
    engine.runAndWait()

def take_command():
    try:
        with sr.Microphone() as source:
            print('listening...')
            voice = listener.listen(source)
            command = listener.recognize_google(voice)
            command = command.lower()
            if 'alexa' in command:
                command = command.replace('alexa', '')
                print(command)
    except:
        pass
    return command

def run_alexa():
    command = take_command()
    print(command)
    if 'play' in command:
        song = command.replace('play', '')
        talk('playing ' + song)
        pywhatkit.playonyt(song)
    elif 'time' in command:
        time = datetime.datetime.now().strftime('%I:%M %p')
        talk('Current time is ' + time)
    elif 'who the heck is' in command:
        person = command.replace('who the heck is', '')
        info = wikipedia.summary(person, 1)
        print(info)
        talk(info)
    elif 'date' in command:
        talk('sorry, I have a headache')
    elif 'are you single' in command:
        talk('I am in a relationship with wifi')
    elif 'joke' in command:
        talk(pyjokes.get_joke())
    else:
        talk('Please say the command again.')

while True:
    run_alexa()`

And the Output

`C:\Users\Admin\AppData\Local\Programs\Python\Python39\python.exe C:/Users/Admin/PycharmProjects1/main.py
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects1\main.py", line 60, in <module>
    run_alexa()
  File "C:\Users\Admin\PycharmProjects1\main.py", line 35, in run_alexa
    command = take_command()
  File "C:\Users\Admin\PycharmProjects1\main.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

Process finished with exit code 1`

**Comment by Pluckhimout** [comment]
sorry

**Comment by ashraf-minhaj** [comment]
Please see issue #5
