### ISSUE TITLE
UnboundLocalError: local variable 'command' referenced before assignment

### ISSUE THREAD

**Issue by threadoooor** [ProgrammingHero1/romantic-alexa#54]
I've spent some time in the issues section, and found issue #5. I fixed the problem with it running, however after a certain period of time it times out and gives me "UnboundLocalError: local variable 'command' referenced before assignment", which I read happens if you listener returns none.

How do I prevent this from happening? For example, if I want it to always run in the backround so that whenever I use the wake word and then "play" and a song name, it pulls it up? I find it annoying to have to run it every time.

Thanks for any help!

**Comment by threadoooor** [comment]
Nevermind, I fixed the problem by adding 
command = "waiting"
before
command = listener.recognize_google(voice)
command = command.lower()

I also edited voice = listener.listen(source) to be
voice = listener.listen(source, phrase_time_limit=6, timeout=3600)
and those parameters work better, it makes a new line of text every 6 seconds (you can edit this by changing the number) so if there's backround noise picked up by your microphone it won't take several minutes to run your command.
It also fixes an issue I had where if I was talking to someone, the entire conversation would be recorded and then it would take several minutes to finally output the huge block of text with maybe one command in it. This way the program always runs in the backround and listens for commands, and will stop after 3600 seconds of no mic input (1 hour)

Additionally, I added
    elif 'go to sleep' in command:
        talk('shutting down. see you later')
        stop_alexa()

and the command "stop_alexa()" doesn't exist so it just gives an error and stops the program.

I've done a huge amount with the original program, including google searches, advanced wikipedia searches, ai chatbot implementation, and much more.

**Comment by BenEgeTR** [comment]
can you send your code to me becasue i still cant solve it

**Comment by Prince2347X** [comment]
> can you send your code to me becasue i still cant solve it

Check this https://github.com/ProgrammingHero1/romantic-alexa/issues/57#issuecomment-782789712
