### ISSUE TITLE
how to solve this errors?

### ISSUE THREAD

**Issue by Sinuro** [ProgrammingHero1/romantic-alexa#6]
Traceback (most recent call last):
  File "c:\Users\users\Documents\Programming\Python\AI\Virtual Assistant.py", line 63, in <module>
    run_alexa()
  File "c:\Users\users\Documents\Programming\Python\AI\Virtual Assistant.py", line 38, in run_alexa
    command = take_command()
  File "c:\Users\users\Documents\Programming\Python\AI\Virtual Assistant.py", line 34, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

Windows 10
VS Code

thanks in advance

**Comment by atulnagane45** [comment]
pip3 install pyAudio

**Comment by atulnagane45** [comment]
> Traceback (most recent call last):
> File "c:\Users\users\Documents\Programming\Python\AI\Virtual Assistant.py", line 63, in
> run_alexa()
> File "c:\Users\users\Documents\Programming\Python\AI\Virtual Assistant.py", line 38, in run_alexa
> command = take_command()
> File "c:\Users\users\Documents\Programming\Python\AI\Virtual Assistant.py", line 34, in take_command
> return command
> UnboundLocalError: local variable 'command' referenced before assignment
> 
> Windows 10
> VS Code
> 
> thanks in advance

make sure you have install pyAudio

**Comment by Sinuro** [comment]
> > Traceback (most recent call last):
> > File "c:\Users\users\Documents\Programming\Python\AI\Virtual Assistant.py", line 63, in
> > run_alexa()
> > File "c:\Users\users\Documents\Programming\Python\AI\Virtual Assistant.py", line 38, in run_alexa
> > command = take_command()
> > File "c:\Users\users\Documents\Programming\Python\AI\Virtual Assistant.py", line 34, in take_command
> > return command
> > UnboundLocalError: local variable 'command' referenced before assignment
> > Windows 10
> > VS Code
> > thanks in advance
> 
> make sure you have install pyAudio

i have installed PyAudio and the result still have the errors like this:

listening...
what time is it
Current time is 04:54 PM
listening...
Traceback (most recent call last):
  File "c:\Users\user\Documents\Programming\Python\AI\Virtual_Assistant.py", line 62, in <module> 
    run_alexa()
  File "c:\Users\user\Documents\Programming\Python\AI\Virtual_Assistant.py", line 36, in run_alexa
    command = take_command()
  File "c:\Users\user\Documents\Programming\Python\AI\Virtual_Assistant.py", line 32, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

the code run properly, but still have errors in the end

**Comment by atulnagane45** [comment]
ok then declare the command variable the outside the function like
command  = ''



```
import speech_recognition as sr
import pyttsx3
import pywhatkit
import datetime
import wikipedia
import pyjokes

listener = sr.Recognizer()
engine = pyttsx3.init()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)
command = ''

def talk(text):
    engine.say(text)
    engine.runAndWait()


def take_command():
    try:
        with sr.Microphone() as source:
            print('listening...')
            listener.adjust_for_ambient_noise(source,duration=1)
            voice = listener.listen(source)
            print("$$$$$$$@@@@")
            command = listener.recognize_google(voice)
            command = command.lower()
            if 'alexa' in command:
                command = command.replace('alexa', '')
                print(command)
    except:
        pass
    return command


def run_alexa():
    command = take_command()
    print(command)
    if 'play' in command:
        song = command.replace('play', '')
        talk('playing ' + song)
        pywhatkit.playonyt(song)
    elif 'time' in command:
        time = datetime.datetime.now().strftime('%I:%M %p')
        talk('Current time is ' + time)
    elif 'who the heck is' in command:
        person = command.replace('who the heck is', '')
        info = wikipedia.summary(person, 1)
        print(info)
        talk(info)
    elif 'date' in command:
        talk('sorry, I have a headache')
    elif 'are you single' in command:
        talk('I am in a relationship with wifi')
    elif 'joke' in command:
        talk(pyjokes.get_joke())
    else:
        talk('Please say the command again.')


while True:
    run_alexa()

```

**Comment by FullStackParihar** [comment]
I'm facing module error!!
"Modules not defined"

**Comment by Sinuro** [comment]
> ok then declare the command variable the outside the function like
> command = ''
> 
> ```
> import speech_recognition as sr
> import pyttsx3
> import pywhatkit
> import datetime
> import wikipedia
> import pyjokes
> 
> listener = sr.Recognizer()
> engine = pyttsx3.init()
> voices = engine.getProperty('voices')
> engine.setProperty('voice', voices[1].id)
> command = ''
> 
> def talk(text):
>     engine.say(text)
>     engine.runAndWait()
> 
> 
> def take_command():
>     try:
>         with sr.Microphone() as source:
>             print('listening...')
>             listener.adjust_for_ambient_noise(source,duration=1)
>             voice = listener.listen(source)
>             print("$$$$$$$@@@@")
>             command = listener.recognize_google(voice)
>             command = command.lower()
>             if 'alexa' in command:
>                 command = command.replace('alexa', '')
>                 print(command)
>     except:
>         pass
>     return command
> 
> 
> def run_alexa():
>     command = take_command()
>     print(command)
>     if 'play' in command:
>         song = command.replace('play', '')
>         talk('playing ' + song)
>         pywhatkit.playonyt(song)
>     elif 'time' in command:
>         time = datetime.datetime.now().strftime('%I:%M %p')
>         talk('Current time is ' + time)
>     elif 'who the heck is' in command:
>         person = command.replace('who the heck is', '')
>         info = wikipedia.summary(person, 1)
>         print(info)
>         talk(info)
>     elif 'date' in command:
>         talk('sorry, I have a headache')
>     elif 'are you single' in command:
>         talk('I am in a relationship with wifi')
>     elif 'joke' in command:
>         talk(pyjokes.get_joke())
>     else:
>         talk('Please say the command again.')
> 
> 
> while True:
>     run_alexa()
> ```

i did what you write here, but the result:

listening...
$$$$$$$@@@@
what time now
Current time is 10:49 PM
listening...
$$$$$$$@@@@
Traceback (most recent call last):
  File "c:\Users\user\Documents\Programming\Python\AI\Virtual_Assistant.py", line 64, in <module>
    run_alexa()
  File "c:\Users\user\Documents\Programming\Python\AI\Virtual_Assistant.py", line 38, in run_alexa
    command = take_command()
  File "c:\Users\user\Documents\Programming\Python\AI\Virtual_Assistant.py", line 34, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

the issue still exist, i dont know why

**Comment by AshwinRaikar88** [comment]
Hello, I've resolved this issue ....use this code 
The program will run forever

```python
import speech_recognition as sr
import pyttsx3
import pywhatkit
import datetime
import wikipedia
import pyjokes

listener = sr.Recognizer()
engine = pyttsx3.init()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)


def talk(text):
    engine.say(text)
    engine.runAndWait()


def take_command():
    try:
        with sr.Microphone() as source:
            print('listening...')
            voice = listener.listen(source)
            command = listener.recognize_google(voice)
            command = command.lower()
            if 'alexa' in command:
                command = command.replace('alexa', '')
                print(command)
            return command
    except:
        pass



def run_alexa():
    command = take_command()
    print(command)

    if command == None:
        talk('say something')
        print("Say something")
    elif 'play' in command:
        song = command.replace('play', '')
        talk('playing ' + song)
        pywhatkit.playonyt(song)
    elif 'time' in command:
        time = datetime.datetime.now().strftime('%I:%M %p')
        talk('Current time is ' + time)
    elif 'who the heck is' in command:
        person = command.replace('who the heck is', '')
        info = wikipedia.summary(person, 1)
        print(info)
        talk(info)
    elif 'date' in command:
        talk('sorry, I have a headache')
    elif 'are you single' in command:
        talk('I am in a relationship with wifi')
    elif 'joke' in command:
        talk(pyjokes.get_joke())
    else:
        talk('Please say the command again.')


while True:
    run_alexa()
```

The solution was to return the command in the try block of the take_command()
For every new iteration that has no command the calling function will crash as it will be not defined 

Nice work with with this project, keep making cool projects  👍

**Comment by AshwinRaikar88** [comment]
> > ok then declare the command variable the outside the function like
> > command = ''
> > ```
> > import speech_recognition as sr
> > import pyttsx3
> > import pywhatkit
> > import datetime
> > import wikipedia
> > import pyjokes
> > 
> > listener = sr.Recognizer()
> > engine = pyttsx3.init()
> > voices = engine.getProperty('voices')
> > engine.setProperty('voice', voices[1].id)
> > command = ''
> > 
> > def talk(text):
> >     engine.say(text)
> >     engine.runAndWait()
> > 
> > 
> > def take_command():
> >     try:
> >         with sr.Microphone() as source:
> >             print('listening...')
> >             listener.adjust_for_ambient_noise(source,duration=1)
> >             voice = listener.listen(source)
> >             print("$$$$$$$@@@@")
> >             command = listener.recognize_google(voice)
> >             command = command.lower()
> >             if 'alexa' in command:
> >                 command = command.replace('alexa', '')
> >                 print(command)
> >     except:
> >         pass
> >     return command
> > 
> > 
> > def run_alexa():
> >     command = take_command()
> >     print(command)
> >     if 'play' in command:
> >         song = command.replace('play', '')
> >         talk('playing ' + song)
> >         pywhatkit.playonyt(song)
> >     elif 'time' in command:
> >         time = datetime.datetime.now().strftime('%I:%M %p')
> >         talk('Current time is ' + time)
> >     elif 'who the heck is' in command:
> >         person = command.replace('who the heck is', '')
> >         info = wikipedia.summary(person, 1)
> >         print(info)
> >         talk(info)
> >     elif 'date' in command:
> >         talk('sorry, I have a headache')
> >     elif 'are you single' in command:
> >         talk('I am in a relationship with wifi')
> >     elif 'joke' in command:
> >         talk(pyjokes.get_joke())
> >     else:
> >         talk('Please say the command again.')
> > 
> > 
> > while True:
> >     run_alexa()
> > ```
> 
> i did what you write here, but the result:
> 
> listening...
> $$$$$$$@@@@
> what time now
> Current time is 10:49 PM
> listening...
> $$$$$$$@@@@
> Traceback (most recent call last):
> File "c:\Users\user\Documents\Programming\Python\AI\Virtual_Assistant.py", line 64, in
> run_alexa()
> File "c:\Users\user\Documents\Programming\Python\AI\Virtual_Assistant.py", line 38, in run_alexa
> command = take_command()
> File "c:\Users\user\Documents\Programming\Python\AI\Virtual_Assistant.py", line 34, in take_command
> return command
> UnboundLocalError: local variable 'command' referenced before assignment
> 
> the issue still exist, i dont know why

The solution was to return the command in the try block of the take_command()
For every new iteration that has no command the calling function will crash as it will be not defined 

Nice work with with this project, keep making cool projects  👍

**Comment by Sinuro** [comment]
> Hello, I've resolved this issue ....use this code
> The program will run forever
> 
> ```python
> import speech_recognition as sr
> import pyttsx3
> import pywhatkit
> import datetime
> import wikipedia
> import pyjokes
> 
> listener = sr.Recognizer()
> engine = pyttsx3.init()
> voices = engine.getProperty('voices')
> engine.setProperty('voice', voices[1].id)
> 
> 
> def talk(text):
>     engine.say(text)
>     engine.runAndWait()
> 
> 
> def take_command():
>     try:
>         with sr.Microphone() as source:
>             print('listening...')
>             voice = listener.listen(source)
>             command = listener.recognize_google(voice)
>             command = command.lower()
>             if 'alexa' in command:
>                 command = command.replace('alexa', '')
>                 print(command)
>             return command
>     except:
>         pass
> 
> 
> 
> def run_alexa():
>     command = take_command()
>     print(command)
> 
>     if command == None:
>         talk('say something')
>         print("Say something")
>     elif 'play' in command:
>         song = command.replace('play', '')
>         talk('playing ' + song)
>         pywhatkit.playonyt(song)
>     elif 'time' in command:
>         time = datetime.datetime.now().strftime('%I:%M %p')
>         talk('Current time is ' + time)
>     elif 'who the heck is' in command:
>         person = command.replace('who the heck is', '')
>         info = wikipedia.summary(person, 1)
>         print(info)
>         talk(info)
>     elif 'date' in command:
>         talk('sorry, I have a headache')
>     elif 'are you single' in command:
>         talk('I am in a relationship with wifi')
>     elif 'joke' in command:
>         talk(pyjokes.get_joke())
>     else:
>         talk('Please say the command again.')
> 
> 
> while True:
>     run_alexa()
> ```
> 
> The solution was to return the command in the try block of the take_command()
> For every new iteration that has no command the calling function will crash as it will be not defined
> 
> Nice work with with this project, keep making cool projects 👍

nice, it's works.
but i want to ask, how can i setting the alexa speed voice? i think the alexa voice is too fast

**Comment by ashraf-minhaj** [comment]
Guys, in python you don't need to declare a variable like you do in C, CPP etc. 
It is throwing the error because the listener returns None. You need to have a good internet connection for the Google Speech Recognition API to work.

**Comment by ashraf-minhaj** [comment]
> but i want to ask, how can i setting the alexa speed voice? i think the alexa voice is too fast

Use this - 
`pyttsx3.setProperty('rate', 80)`

for 80 words per minute.
