### ISSUE TITLE
Having problem in the 'While True: ' loop as alexa is not listening me again.

### ISSUE THREAD

**Issue by aamirhussain350** [ProgrammingHero1/romantic-alexa#62]
C:\Users\aamir\PycharmProjects\leisure_work\venv\Scripts\python.exe C:/Users/aamir/PycharmProjects/leisure_work/alexa.py
listening...
play justin bieber song
play justin bieber song
listening...

I am having this issue:
My issue is: Alexa is not hearing me again or it is not taking the command. Only 'listening...' shows but Alexa didn't respond. The 'While True: ' loop is not working. The microphone shows working in systems notification area, but alexa is not responding.

Any solution would be great

**Comment by ashraf-minhaj** [comment]
It depends completely on your computer. 
One thing you can do is, hardcode a time, the loop will listen till that time and iterate.

**Comment by jmherrera11** [comment]
Maybe there is a better solution but this works for me:

while True:
    try:
        run_alexa()
    except UnboundLocalError:
        print("No command detected! Alexa has stopped working ")
        command = "."
