### ISSUE TITLE
import speech_recognition as sr ModuleNotFoundError: No module named 'speech_recognition'

### ISSUE THREAD

**Issue by varungolusupudi** [ProgrammingHero1/romantic-alexa#7]
I installed all the modules given in the readMe from vs code terminal. When I run the program, I get this error saying that the modules are not found. Please help me with this.

**Comment by ghost** [comment]
``

Try pip install SpeechRecognition
On your terminal

**Comment by varungolusupudi** [comment]
It is showing the following "Requirement already satisfied: SpeechRecognition in c:\users\user_name\appdata\local\programs\python\python38-32\lib\site-packages (3.8.1)"

**Comment by ashraf-minhaj** [comment]
> I installed all the modules given in the readMe from vs code terminal. When I run the program, I get this error saying that the modules are not found. Please help me with this.

Perhaps you haven't added Python to your environment variable path. Try reinstalling or modify installation and add it to your path.
