### ISSUE TITLE
pip3 install pyAudio       

### ISSUE THREAD

**Issue by shwandastan** [ProgrammingHero1/romantic-alexa#88]
pip3 install pyAudio                                               130 ⨯
Collecting pyAudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Building wheels for collected packages: pyAudio
  Building wheel for pyAudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gcpsfh7o/pyaudio_ca6fefffcf454d01a681ee6d26aa6619/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gcpsfh7o/pyaudio_ca6fefffcf454d01a681ee6d26aa6619/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-o76hod5l
       cwd: /tmp/pip-install-gcpsfh7o/pyaudio_ca6fefffcf454d01a681ee6d26aa6619/
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  copying src/pyaudio.py -> build/lib.linux-x86_64-3.9
  running build_ext                                                          
  building '_portaudio' extension                                            
  creating build/temp.linux-x86_64-3.9                                       
  creating build/temp.linux-x86_64-3.9/src                                   
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.9/src/_portaudiomodule.o                                            
  src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or directory                                                                       
     29 | #include "portaudio.h"                                             
        |          ^~~~~~~~~~~~~                                             
  compilation terminated.                                                    
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1     
  ----------------------------------------                                   
  ERROR: Failed building wheel for pyAudio
  Running setup.py clean for pyAudio
Failed to build pyAudio
Installing collected packages: pyAudio
    Running setup.py install for pyAudio ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gcpsfh7o/pyaudio_ca6fefffcf454d01a681ee6d26aa6619/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gcpsfh7o/pyaudio_ca6fefffcf454d01a681ee6d26aa6619/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1pl_kc1i/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/shawn/.local/include/python3.9/pyAudio 
         cwd: /tmp/pip-install-gcpsfh7o/pyaudio_ca6fefffcf454d01a681ee6d26aa6619/                                                                         
    Complete output (16 lines):                                              
    running install                                                          
    running build                                                            
    running build_py                                                         
    creating build                                                           
    creating build/lib.linux-x86_64-3.9                                      
    copying src/pyaudio.py -> build/lib.linux-x86_64-3.9                     
    running build_ext                                                        
    building '_portaudio' extension                                          
    creating build/temp.linux-x86_64-3.9                                     
    creating build/temp.linux-x86_64-3.9/src                                 
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.9/src/_portaudiomodule.o                                          
    src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or directory                                                                     
       29 | #include "portaudio.h"                                           
          |          ^~~~~~~~~~~~~                                           
    compilation terminated.                                                  
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1   
    ----------------------------------------                                 
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gcpsfh7o/pyaudio_ca6fefffcf454d01a681ee6d26aa6619/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gcpsfh7o/pyaudio_ca6fefffcf454d01a681ee6d26aa6619/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1pl_kc1i/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/shawn/.local/include/python3.9/pyAudio Check the logs for full command output.

**Comment by yotonz** [comment]
for linux distro..

1,First we need to install portaudio modules: sudo apt-get install libasound-dev

2,Download the portaudio archive from: http://files.portaudio.com/download.html

3,Unzip the archive: tar -zxvf [portaudio.tgz]

4,Enter the directory, then run: ./configure && make

5,Install: sudo make install

And finally: sudo pip install pyaudio

**Comment by Mrinank-Bhowmick** [comment]
you can try
pip install pipwin
pipwin install pyaudio
In terminal.
Hope that helps
