### ISSUE TITLE
code not running with this issue..

### ISSUE THREAD

**Issue by Inderjeet8826** [ProgrammingHero1/romantic-alexa#96]
Traceback (most recent call last):
  File "D:\python\alexa.py", line 60, in <module>
    run_alexa()
  File "D:\python\alexa.py", line 35, in run_alexa
    command = take_command()
  File "D:\python\alexa.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by Smitthyy** [comment]
I found that this was down to an issue with pyaudio not installing on my Python version, I had to change to Python 3.6 in PyCharm then I was able to install again using pip install pyaudio

**Comment by jmherrera11** [comment]
"Generally this error occurs when the pyaudio module is not installed properly ,sounds wierd but you can try
pip install pipwin
pipwin install pyaudio
In terminal.
Hope that helps"  ---->>>> IT WORKED X ME. Thanks EFFLUX110

**Comment by jmherrera11** [comment]
and this:

while True:
    try:
        run_alexa()
    except UnboundLocalError:
        print("No command detected! Alexa has stopped working ")
        command = "."
